-file("/usr/local/Cellar/erlang/26.2.1/lib/erlang/lib/parsetools-2.5/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(per_lex).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/per_lex.xrl", 41).

-file("/usr/local/Cellar/erlang/26.2.1/lib/erlang/lib/parsetools-2.5/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

%% string(InChars) ->
%% string(InChars, Loc) ->
%% {ok,Tokens,EndLoc} | {error,ErrorInfo,EndLoc}.
%% Loc is the starting location of the token, while EndLoc is the first not scanned
%% location. Location is either Line or {Line,Column}, depending on the "error_location" option.

string(Ics) -> 
    string(Ics,1).
string(Ics,L0) -> 
    string(Ics, L0, 1, Ics, []).
string(Ics, L0, C0, Tcs, Ts) -> 
    case do_string(Ics, L0, C0, Tcs, Ts) of
        {ok, T, {L,_}} -> {ok, T, L};
        {error, {{EL,_},M,D}, {L,_}} ->
            EI = {EL,M,D},
            {error, EI, L}
    end.

do_string([], L, C, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),{L,C}};
do_string(Ics0, L0, C0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, C0, 0, reject, 0) of
        {A,Alen,Ics1,L1,_C1} ->                  % Accepting end state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {A,Alen,Ics1,L1,_C1,_S1} ->              % Accepting transition state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {reject,_Alen,Tlen,_Ics1,_L1,_C1,_S1} ->  % After a non-accepting state
            {error,{{L0, C0} ,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},{L0, C0}};
        {A,Alen,Tlen,_Ics1,L1, C1,_S1}->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            C2 = adjust_col(Tcs, Alen, C1),
            string_cont(Tcs1, L2, C2, yyaction(A, Alen, Tcs, L0,C0), Ts)
    end.

%% string_cont(RestChars, Line, Col, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/5}).

string_cont(Rest, Line, Col, {token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, skip_token, Ts) ->
    do_string(Rest, Line, Col, Rest, Ts);
string_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, Ts);
string_cont(_Rest, Line, Col, {error,S}, _Ts) ->
    {error,{{Line, Col},?MODULE,{user,S}},{Line,Col}}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCol,AccAction,AccLen}

token(Cont,Chars) -> 
    token(Cont,Chars,1).
token(Cont, Chars, Line) -> 
    case do_token(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_token([], Chars, Line, Col) ->
    token(yystate(), Chars, Line, Col, Chars, 0, Line, Col, reject, 0);
do_token({token,State,Line,Col,Tcs,Tlen,Tline,Tcol,Action,Alen}, Chars, _, _) ->
    token(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Action, Alen).

%% token(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Alen1,Tline,Tcol,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     true -> {eof,{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,_L1,_C1,_S1} ->    % No token match
            Error = {{Tline,Tcol},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,{Tline,Tcol}},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            token_cont(Tcs1, L2, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol))
    end.

%% token_cont(RestChars, Line, Col, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/4}).

token_cont(Rest, Line, Col, {token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, {end_token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, skip_token) ->
    token(yystate(), Rest, Line, Col, Rest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {error,S}) ->
    {done,{error,{{Line, Col},?MODULE,{user,S}},{Line, Col}},Rest}.

%% tokens(Continuation, Chars) ->
%% tokens(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Error,AccAction,AccLen}

tokens(Cont,Chars) -> 
    tokens(Cont,Chars,1).
tokens(Cont, Chars, Line) -> 
    case do_tokens(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_tokens([], Chars, Line, Col) ->
    tokens(yystate(), Chars, Line, Col, Chars, 0, Line, Col, [], reject, 0);
do_tokens({tokens,State,Line,Col,Tcs,Tlen,Tline,Tcol,Ts,Action,Alen}, Chars, _,_) ->
    tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Ts, Action, Alen);
do_tokens({skip_tokens,State,Line, Col, Tcs,Tlen,Tline,Tcol,Error,Action,Alen}, Chars, _,_) ->
    skip_tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Error, Action, Alen).

%% tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol,Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     Ts == [] -> {eof,{L1,C1}};
                     true -> {ok,yyrev(Ts),{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            %% Skip rest of tokens.
            Error = {{L1,C1},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline,Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            tokens_cont(Tcs1, L2, C2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Column, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/5}).

tokens_cont(Rest, Line, Col, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),{Line,Col}},Rest};
tokens_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),{Line, Col}},NewRest};
tokens_cont(Rest, Line, Col, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, Col, {{Line,Col},?MODULE,{user,S}}).

%% skip_tokens(InChars, Line, Col, Error) -> {done,{error,Error,{Line,Col}},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Col, Error) ->
    skip_tokens(yystate(), Ics, Line, Col, Ics, 0, Line, Col, Error, reject, 0).

%% skip_tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1, C1} ->                  % Accepting end state
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,[],L1,C1, S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,C1,_S1} ->
            {done,{error,Error,{L1,C1}},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1,Error);
        {A1,Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline, Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, C1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Col, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/5}).

skip_cont(Rest, Line, Col, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {end_token,_T}, Error) ->
    {done,{error,Error,{Line,Col}},Rest};
skip_cont(Rest, Line, Col, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,{Line,Col}},NewRest};
skip_cont(Rest, Line, Col, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% adjust_col(Chars, AcceptLength, Col) -> NewCol
%% Handle newlines, tabs and unicode chars.
adjust_col(_, 0, Col) ->
    Col;
adjust_col([$\n | R], L, _) ->
    adjust_col(R, L-1, 1);
adjust_col([$\t | R], L, Col) ->
    adjust_col(R, L-1, tab_forward(Col)+1);
adjust_col([C | R], L, Col) when C>=0 andalso C=< 16#7F ->
    adjust_col(R, L-1, Col+1);
adjust_col([C | R], L, Col) when C>= 16#80 andalso C=< 16#7FF ->
    adjust_col(R, L-1, Col+2);
adjust_col([C | R], L, Col) when C>= 16#800 andalso C=< 16#FFFF ->
    adjust_col(R, L-1, Col+3);
adjust_col([C | R], L, Col) when C>= 16#10000 andalso C=< 16#10FFFF ->
    adjust_col(R, L-1, Col+4).

tab_forward(C) ->
    D = C rem tab_size(),
    A = tab_size()-D,
    C+A.

tab_size() -> 8.

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, Col, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line, Col} |
%% {Action, AcceptLen, RestChars, Line, Col, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, Col, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, Col, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/per_lex.erl", 339).
yystate() -> 28.

yystate(35, [117|Ics], Line, Col, Tlen, _, _) ->
    yystate(29, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(35, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,35};
yystate(34, [110|Ics], Line, Col, Tlen, _, _) ->
    yystate(30, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(34, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,34};
yystate(33, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [62|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(33, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,33};
yystate(32, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(16, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(32, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(32, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(32, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(32, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(32, Ics, Line+1, 1, Tlen+1, 10, Tlen);
yystate(32, Ics, Line, Col, Tlen, _, _) ->
    {10,Tlen,Ics,Line,Col,32};
yystate(31, [100|Ics], Line, Col, Tlen, _, _) ->
    yystate(35, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(31, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,31};
yystate(30, [100|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(30, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,30};
yystate(29, [108|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(29, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,29};
yystate(28, [8594|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [1055|Ics], Line, Col, Tlen, _, _) ->
    yystate(12, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [955|Ics], Line, Col, Tlen, _, _) ->
    yystate(4, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [931|Ics], Line, Col, Tlen, _, _) ->
    yystate(3, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [929|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [930|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [928|Ics], Line, Col, Tlen, _, _) ->
    yystate(11, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [206|Ics], Line, Col, Tlen, _, _) ->
    yystate(19, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [125|Ics], Line, Col, Tlen, _, _) ->
    yystate(7, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [124|Ics], Line, Col, Tlen, _, _) ->
    yystate(15, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [123|Ics], Line, Col, Tlen, _, _) ->
    yystate(7, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [109|Ics], Line, Col, Tlen, _, _) ->
    yystate(23, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [105|Ics], Line, Col, Tlen, _, _) ->
    yystate(5, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(34, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [100|Ics], Line, Col, Tlen, _, _) ->
    yystate(22, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(7, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [92|Ics], Line, Col, Tlen, _, _) ->
    yystate(6, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(7, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [86|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [85|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [64|Ics], Line, Col, Tlen, _, _) ->
    yystate(15, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [62|Ics], Line, Col, Tlen, _, _) ->
    yystate(7, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(15, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [60|Ics], Line, Col, Tlen, _, _) ->
    yystate(7, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(1, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(9, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [47|Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(15, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(33, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [44|Ics], Line, Col, Tlen, _, _) ->
    yystate(15, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(7, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [41|Ics], Line, Col, Tlen, _, _) ->
    yystate(7, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(8, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(8, Ics, Line+1, 1, Tlen+1, 2, Tlen);
yystate(28, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 87, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 104 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 106, C =< 108 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 205 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 207, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 927 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 932, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(28, Ics, Line, Col, Tlen, _, _) ->
    {2,Tlen,Ics,Line,Col,28};
yystate(27, [8594|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [955|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [944|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [96|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [44|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [41|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [11|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(32, Ics, Line+1, 1, Tlen+1, 8, Tlen);
yystate(27, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 33, C =< 38 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 60, C =< 64 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 123, C =< 127 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 256, C =< 687 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 752, C =< 911 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 1024, C =< 7487 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 7504, C =< 8207 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 8602, C =< 8607 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 9760, C =< 12287 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 12320, C =< 120767 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(27, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 120784 ->
    yystate(24, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(27, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,27};
yystate(26, [116|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(26, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,26};
yystate(25, Ics, Line, Col, Tlen, _, _) ->
    {5,Tlen,Ics,Line,Col};
yystate(24, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(24, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(24, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(24, [11|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(24, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(24, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(32, Ics, Line+1, 1, Tlen+1, 10, Tlen);
yystate(24, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 33, C =< 44 ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 46 ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(24, Ics, Line, Col, Tlen, _, _) ->
    {10,Tlen,Ics,Line,Col,24};
yystate(23, [111|Ics], Line, Col, Tlen, _, _) ->
    yystate(31, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(23, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,23};
yystate(22, [111|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(14, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 110 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(22, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,22};
yystate(21, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(21, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,21};
yystate(20, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col};
yystate(19, [163|Ics], Line, Col, Tlen, _, _) ->
    yystate(3, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [161|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [162|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [160|Ics], Line, Col, Tlen, _, _) ->
    yystate(11, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 159 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 164, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(19, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,19};
yystate(18, [114|Ics], Line, Col, Tlen, _, _) ->
    yystate(26, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(18, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,18};
yystate(17, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [92|Ics], Line, Col, Tlen, _, _) ->
    yystate(25, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(17, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,17};
yystate(16, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,16};
yystate(15, Ics, Line, Col, Tlen, _, _) ->
    {2,Tlen,Ics,Line,Col};
yystate(14, [102|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(14, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,14};
yystate(13, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(13, Ics, Line, Col, Tlen, _, _) ->
    {0,Tlen,Ics,Line,Col,13};
yystate(12, Ics, Line, Col, Tlen, _, _) ->
    {4,Tlen,Ics,Line,Col};
yystate(11, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(11, Ics, Line, Col, Tlen, _, _) ->
    {4,Tlen,Ics,Line,Col,11};
yystate(10, [111|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(10, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,10};
yystate(9, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(15, Ics, Line, Col, Tlen+1, 1, Tlen);
yystate(9, Ics, Line, Col, Tlen, _, _) ->
    {1,Tlen,Ics,Line,Col,9};
yystate(8, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(16, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(8, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(8, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(8, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(8, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(8, Ics, Line+1, 1, Tlen+1, 9, Tlen);
yystate(8, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(8, Ics, Line, Col, Tlen, _, _) ->
    {9,Tlen,Ics,Line,Col,8};
yystate(7, Ics, Line, Col, Tlen, _, _) ->
    {1,Tlen,Ics,Line,Col};
yystate(6, [47|Ics], Line, Col, Tlen, _, _) ->
    yystate(12, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(6, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,6};
yystate(5, [109|Ics], Line, Col, Tlen, _, _) ->
    yystate(2, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(5, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,5};
yystate(4, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col};
yystate(3, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 6, Tlen);
yystate(3, Ics, Line, Col, Tlen, _, _) ->
    {6,Tlen,Ics,Line,Col,3};
yystate(2, [112|Ics], Line, Col, Tlen, _, _) ->
    yystate(10, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(2, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,2};
yystate(1, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(1, Ics, Line, Col, Tlen, _, _) ->
    {2,Tlen,Ics,Line,Col,1};
yystate(0, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [59|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [42|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [39|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 47, C =< 57 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 128, C =< 255 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 688, C =< 751 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 912, C =< 943 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 945, C =< 954 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 956, C =< 1023 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 7488, C =< 7503 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 8208, C =< 8593 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 8595, C =< 8601 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 8608, C =< 9759 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 12288, C =< 12319 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, [C|Ics], Line, Col, Tlen, _, _) when C >= 120768, C =< 120783 ->
    yystate(0, Ics, Line, Col, Tlen+1, 8, Tlen);
yystate(0, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col,0};
yystate(S, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine, TokenCol) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, _, _, TokenLine, _) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine, _) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine, _) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine, _) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine, _) ->
    yyaction_7(TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, _, _, _, _) ->
    yyaction_9();
yyaction(10, _, _, _, _) ->
    yyaction_10();
yyaction(_, _, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("src/per_lex.xrl", 27).
yyaction_0(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_1/2}).
-file("src/per_lex.xrl", 28).
yyaction_1(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_2/2}).
-file("src/per_lex.xrl", 29).
yyaction_2(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_3/1}).
-file("src/per_lex.xrl", 30).
yyaction_3(TokenLine) ->
     { token, { arrow, TokenLine } } .

-compile({inline,yyaction_4/1}).
-file("src/per_lex.xrl", 31).
yyaction_4(TokenLine) ->
     { token, { forall, TokenLine } } .

-compile({inline,yyaction_5/1}).
-file("src/per_lex.xrl", 32).
yyaction_5(TokenLine) ->
     { token, { meet, TokenLine } } .

-compile({inline,yyaction_6/1}).
-file("src/per_lex.xrl", 33).
yyaction_6(TokenLine) ->
     { token, { sigma, TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("src/per_lex.xrl", 34).
yyaction_7(TokenLine) ->
     { token, { lam, TokenLine } } .

-compile({inline,yyaction_8/2}).
-file("src/per_lex.xrl", 35).
yyaction_8(TokenChars, TokenLine) ->
     { token, { id, TokenLine, unicode : characters_to_binary (TokenChars) } } .

-compile({inline,yyaction_9/0}).
-file("src/per_lex.xrl", 36).
yyaction_9() ->
     skip_token .

-compile({inline,yyaction_10/0}).
-file("src/per_lex.xrl", 37).
yyaction_10() ->
     skip_token .
-file("/usr/local/Cellar/erlang/26.2.1/lib/erlang/lib/parsetools-2.5/include/leexinc.hrl", 344).
